export const initialState = {
  layoutMode: "", // modal, alert, ""
  formOptions: ["Feedback", "Account", "Share"],
  formState: "Account",
  username: "",
  email: "",
  password: "",
  currentPassword: "",
  newPassword: "",
  message: "",
  signedIn: 0,
  connected: 0,
  running: "",
  habits: {
    ids: [1, 2, 3],
    1: { id: 1, name: "walk" },
    2: { id: 2, name: "run" },
    3: { id: 3, name: "lift" },
  },
  satisfied: false,
  score: 42,
  feedback: "",
  isPrivate: true,
  alertHead: "Feedback Received",
  alertMessage: "Thank You!",
  alertColor: "green",
};
